### PR TITLE
Fix for Export-Excel #165

### PR DESCRIPTION
**Pull request by DarkLite1**
Fixed handling of the TableName with parameter validation, we now throw
an error in case the TableName:
- starts with something else then a letter
- is NULL or empty
- Contains spaces
Just like in the orriginal EPPlus.dll library.

Added Try/Catch clause for the End clause. So errors like 'TableName is
not unique' are terminating errors and the function isn't executed any
further.

Also cleaned up for readability some cosmetic stuff:
- 'if(' to 'if ('
- double quotes to single quotes where needed

### CODE REVIEW

**Comment by DarkLite1** [comment]
So Dough, do you think this can be accepted in your branch?

**Comment by dfinke** [comment]
I just need to test it and have a closer look. From what I see, it should be good to go. I should have time by the weekend.

**Comment by dfinke** [comment]
Thanks. This is great. The verbose messages worked out well too.

Doug

**Comment by DarkLite1** [comment]
Agree, it makes things a bit more clear with regards to what is happening behind the scenes. I usually do this all the time in my code, adding verbose messages. When something fails or something isn't quite right, I run it with the `-Verbose` switch. Often this has been a great help to me to pinpoint the problem really fast. Thanks for merging buddy :+1:

**Pull request merged**
