### PR TITLE
Fixes Column order issue

### PR DESCRIPTION
**Pull request by uSlackr**
Column letters were returned out of order.  Issue #708

Not done this before - comments welcome

### CODE REVIEW

**Comment by dfinke** [comment]
Thanks @uSlackr, works. Could possibly add this as a set of separate tests in a new file? Convert the `-eq` to `Should Be`.

```powershell
$map = @{
    1024  = 'AMJ'
    2048  = 'BZT'
    3072  = 'DND'
    4096  = 'FAN'
    5120  = 'GNX'
    6144  = 'IBH'
    7168  = 'JOR'
    8192  = 'LCB'
    9216  = 'MPL'
    10240 = 'OCV'
    11264 = 'PQF'
    12288 = 'RDP'
    13312 = 'SQZ'
    14336 = 'UEJ'
    15360 = 'VRT'
    16384 = 'XFD'
}

(Get-ExcelColumnName 26).columnName -eq 'Z'
(Get-ExcelColumnName 27).columnName -eq 'AA'
(Get-ExcelColumnName 28).columnName -eq 'AB'
(Get-ExcelColumnName 30).columnName -eq 'AD'
(Get-ExcelColumnName 48).columnName -eq 'AV'

1..16 | % {
    $number = $_*1024    
    (Get-ExcelColumnName $number).columnName -eq $map.$number
}
```

**Comment by uSlackr** [comment]
>Thanks @uSlackr, works. Could possibly add this as a set of separate tests in a new file? Convert the -eq to Should Be.

I'll give it a shot!

**Comment by uSlackr** [comment]
Let me know how the test looks.  Complete n00b with here.

**Comment by dfinke** [comment]
Did you add them or you want an example?

**Pull request merged**
