### PR TITLE
Fix for #162 and other improvements

### PR DESCRIPTION
**Pull request by DarkLite1**
Fix for #162 
- Added help text for 'Import-Excel'
- Added 'DataOnly' parameter to 'Import-Excel'
- Improved 'Get-ExcelSheetInfo'

### CODE REVIEW

**Comment by dfinke** [comment]
Awesome PR, even help is in there! I'm reviewing, so far so good. Thanks!

**Comment by DarkLite1** [comment]
Thanks Dough :) It would be great to have this in the master branch, That way we can update the module again from your code without worrying of breaking our current stuff. As we already have these changes in production. 

If you see possibilities to optimize the code. please feel free to do so. I did the best I could.

**Comment by DarkLite1** [comment]
Seems logical to split it up. But then I would maybe suggest to refactor it to one function called'Get-ExcelInfo' with parameters 'Sheet' and 'Workbook'. To avoid duplicating code and keep things simple.

On the topic of adding headers, does it matter? As we only import data and not write it to a sheet.

**Comment by dfinke** [comment]
For the splitting of the functions, do you have two or one function with different params. I prefer the separate functions, that way it is more easily discover it with `Get-Command`. Plus duplication can be eliminated with and "internal" function for shared operations.

Good question on headers. I think it ought to be consistent. I use `Import-Excel` to read sheets, operate/calculate details. Having the headers as data could throw off the counts on things.

What do you think?

**Comment by DarkLite1** [comment]
Yes, if that is the desired behavior then I fully agree with you. Consistency is key! 

With regards to Get-Command you are right. It's easier to find that way.

**Comment by dfinke** [comment]
So, would you be up for making those changes? I'm guessing this is the code you run in your shop? So would these changes break what you're doing?

**Comment by DarkLite1** [comment]
Yup. already done and submitted. Nice catch though with the duplicate header entry :)

All fixed as requested:
- Seperate function for 'Get-ExcelWorkbookInfo'
- Added proper closing of the stream for 'Get-ExcelWorkbookInfo' and 'Get-ExcelSheetInfo'
- Fixed duplicate headers issue with 'DataOnly'

It's always great to have a second pair of eyes. I really appreciate your feedback Doug, keep it comming if you see more issues. Your other request to create a seperate function to open and close the stream can be done when this is accepted in your branck. So we can start with a clean sheet instead of mixing stuff up in one PR.

**Comment by dfinke** [comment]
Awesome! That fix looks good. `Get-ExcelWorkbookInfo` works. I was pleasantly surprise when I look at the implementation that you implemented "piping". Excellent. I'll test a bit more and then merge.

Thanks again.

**Comment by DarkLite1** [comment]
I wanted to do piping to with 'DataOnly' but couldn't figure it out properly.

**Comment by dfinke** [comment]
I guess there are a couple scenarios there. Piping multiple xlsx files and looking at more than a single worksheet in a file and maybe across files

**Comment by dfinke** [comment]
Thank you @DarkLite1, great additions. I've tested and merged your PR. When you get a chance, could you take a look at the Read me and let me know if I need  to update it.

Are you on twitter? If so, let me know your id.

Thanks again

**Comment by DarkLite1** [comment]
Awesome! Appreciate the merge, we can now follow your master branch again :) But I first need to update a small piece of my coffee to use the new Get-ExcelWorkbookInfo function

No, I'm not such a Twitter fan. Some US diplomats are better at that than me ;) But you have my email and Skype if you want to get in touch.

**Comment by dfinke** [comment]
Hey @DarkLite1, just curious if you were able to update to the master branch and if you had any issues?

No rush.

Thanks

**Comment by DarkLite1** [comment]
Yes, I've updated the code to the master branch since 3 days a go I believe. All is still running smooth, no issues so far. Thanks for asking.

**Comment by dfinke** [comment]
Great! Thanks for adding the features and testing it live

**Comment by DarkLite1** [comment]
No problem! We use your code extensively, so if something would be wrong it would pop-up quite fast AND I would let you know asap ;)

**Pull request merged**
