### PR TITLE
Fixed case on file names, and applied a new rules from script analyzer

### PR DESCRIPTION
**Pull request by jhoneill**
Very little functional change - remove-worksheet supports -confirm, and I changed 3 or 4 instances of ::new() to new-object because that will work with PS 4  (we don't expressly want to support 4, but at the same time there's no sense in breaking 4 if we don't need to)
I've made some changes to either bring the code into  line with PSScriptAnalyzer 1.18 guidlines or to tell it where it doesn't need to worry. 
Also fixed a test which didn't work in the appveryor environment.

### CODE REVIEW

**Comment by dfinke** [comment]
Did the new PSSA catch the casing?

**Comment by jhoneill** [comment]
No, it didn't. I installled the  module in cloud-shell and 3 or 4 files were not found. All the changes outside the PSM1 came from PSSA. I've left a couple of the things it doesn't like for now.  Your `if ($x = do-something)` trick gets queried, and I didn't want to disable checks for that, and there is at least one place where there is a plural name which could be re-thought but I'm leaving alone for now.

**Comment by dfinke** [comment]
# Might be a useful report to run on commits

```ps
$xlfile = "$env:TEMP\ScriptAnalyzer.xlsx"
Remove-Item $xlfile -ErrorAction SilentlyContinue

$p = @{
    AutoSize          = $true
    AutoFilter        = $true
    Show              = $true
    IncludePivotTable = $true
    IncludePivotChart = $true
    PivotRows         = 'Severity', 'RuleName'
    PivotData         = @{RuleName = 'Count' } 
    ChartType         = 'BarClustered '
    Activate          = $true
}

Invoke-ScriptAnalyzer . | Export-Excel $xlfile @p
```

image

**Comment by jhoneill** [comment]
@dfinke Genius ! The highest praise I can offer it is to put it straight into my presentation for later ...

**Comment by dfinke** [comment]
# Need to find a different word :-)

You don't do that! Please amplify. Probably will tweet this.

**Plagiarism** is the "wrongful appropriation" and "stealing and publication" of another author's "language, thoughts, ideas, or expressions" and the representation of them as one's own original work.

**Comment by jhoneill** [comment]
@dfinke  
### Research 
(see Tom Lehrer)

**Comment by jhoneill** [comment]
@dfinke I've checked in an example named analyze-this.ps1 
cd ..\GitHub\ImportExcel\
>"." , (dir 'C:\Program Files\WindowsPowerShell\Modules\ImportExcel\')  | .\examples\ScriptAnalyzer\Analyze_this.ps1

produces this which compares the quality over versions 
image

**Comment by dfinke** [comment]
Thanks! Was going to ask. I'll check in the the other too.

**Comment by dfinke** [comment]
Hmm. Don't see it.

**Pull request merged**
