### PR TITLE
ReadMe & Changelog Redux

### PR DESCRIPTION
**Pull request by ImportTaste**
This turned out to be a much larger revision of the documentation than I was originally planning on, and once I got started I wanted to see it through. I split it into three separate commits. 

First and foremost, I moved the Changelog to its own file, keeping only the most recent set of release notes in the ReadMe.

In the Changelog itself, I ended up falling down a rabbit hole of revising older notes to have more consistent syntax, and in the process, and part of that turned into moving the thank-yous to the top of each set of release notes wherever applicable.

Lastly, and most importantly, I added a **Function Overview** to the ReadMe, which did necessitate some minor revisions of the synopses of the help files.

There's a lot of other small tweaks here and there, too many to list, my apologies for that. I sincerely hope to see it used, because on several occasions, I found myself confused on how to use this module and didn't realize where the help files were. (I do know about `Get-Help`, but that required me to know the names of the functions to begin with.)

All I ask in return is that you do not ask for further revisions; I really don't want to touch this again, so use or modify whatever you see fit.

In regards to the work included in this PR, I formally waive any rights granted to me by the Apache-2.0 license. All of it may be applied to this project without my accreditation or further consent.

### CODE REVIEW

**Comment by dfinke** [comment]
Thank you! Much appreciated. Will review. Documentation is definitely a challnge.

**Comment by ImportTaste** [comment]
In hindsight I should've added a commit that included the unmodified changelog and then submitted my modifications in the next commit. Sorry about that.

Because GitHub's syntax highlighting is derping pretty hard on the markdown files, here are direct links to what they look like when rendered:
https://github.com/ImportTaste/ImportExcel/blob/readme-chlog_redux/CHANGELOG.md
https://github.com/ImportTaste/ImportExcel/blob/readme-chlog_redux/README.md

**Comment by dfinke** [comment]
@jhoneill

**Comment by ImportTaste** [comment]
Woops. The links to the function help files didn't have `.md` at the end. Fixed that.

**Comment by dfinke** [comment]
Soon

**Comment by ImportTaste** [comment]
Soon?

**Comment by dfinke** [comment]
Was waiting for @jhoneill to get time to wire in the building of the help into the CI pipeline.

**Comment by ImportTaste** [comment]
.

**Comment by ImportTaste** [comment]
@dfinke Perhaps this could be merged now and the pipeline stuff could come later?

**Comment by ImportTaste** [comment]
@dfinke Perhaps this could be merged now and the pipeline stuff could come later?

I really don't want to have to check recent commits and resolve conflicts again. This was supposed to be one-and-done.

**Comment by ImportTaste** [comment]
Force pushes should be done now. I rebased everything entirely for a cleaner slate and clearer diffs.

**Comment by dfinke** [comment]
Thanks for this. I don't want to keep kicking the can down the road on the CI update. There is lots on the plate at the moment. When I can, I'll look at incorporating this.

**Comment by ImportTaste** [comment]
. . .

**Comment by dfinke** [comment]
Thanks, appreciate the work on this. Closing it for now, will revisit when I have time. Other priorities are calling.

**Comment by ndemou** [comment]
The readme of this project is too big to swallow. It's really hard to find the useful bits. I stumbled upon this issue and the proposed readme seems far better to me. Of course I could be missing hidden drawbacks.

**Pull request closed without merging**
