### PR TITLE
Automatic Documentation Update

### PR DESCRIPTION
**Pull request by thkn-hofa**
I created a workflow that calls 'buildHelp.ps1' when changes in the folder mdHelp are pushed to master. The changes are then automatically committed. 

See issue #1282

### CODE REVIEW

**Comment by thkn-hofa** [comment]
To be a little more clear: 

> The changes are then automatically committed.

This should be 'The changes that were made from this workflow (e.g. the XML) are automatically committed.'

**Comment by dfinke** [comment]
Thanks for PR. The challenge, for me, is not the automation, see below. It is creating the help, maintaining it, and maintaining this part of the pipeline.

Plus, people learn differently, some with this type of help, others with comment based, others with examples, others by reading the source code.

https://github.com/dfinke/ImportExcel/blob/c617d96322c071e04fe2cd1bd6a56911c745e891/CI/build.ps1#L61
https://github.com/dfinke/ImportExcel/blob/c617d96322c071e04fe2cd1bd6a56911c745e891/CI/PS-CI.ps1#L163-L164

**Comment by thkn-hofa** [comment]
Yeah I saw the other issue about documentation but I figured this would at least close the issue I referred.
Feel free to close this PR if you deem it unnecessary.

I had fun looking it up anyway... I'm home sick and I just bought a new keyboard so I was looking for an excuse to test it out.

**Comment by dfinke** [comment]
Haha. Appreciate your input. Hope you'll contribute more.

Feel better, enjoy the keyboard.

**Pull request closed without merging**
