### PR TITLE
Create AddMultiWorkSheet.ps1

### PR DESCRIPTION
**Pull request by conradagramont**
This example shows how to add multiple tabs within the same file.

### CODE REVIEW

**Comment by dfinke** [comment]
@conradagramont Thanks for the example. This can be simplified. You don't need to do the `-PassThru` and  use `Close-ExcelPackage`. Just use ` Export-Excel` and on the last one use the `-Show`. If you can re-work that and commit it, should be able to merge it then.

**Comment by conradagramont** [comment]
Thanks for the for the feedback Doug!  I checked in the change.  It's cool to see that contributing my example actually helped me improve my own code!  Community coding at it's finest!!

**Comment by dfinke** [comment]
Great! Do you have a Twitter handle I can use in the comments?

**Comment by conradagramont** [comment]
Twitter: @agramont

**Pull request merged**
