### PR TITLE
New Get-ExcelTable function

### PR DESCRIPTION
**Pull request by scriptingstudio**
`Get-ExcelTable` function to retrieve Excel table names or table data.
According to #1436, instead of creating separate functions I use a single function to reuse code. Parameter `-content` forces to retrieve data. The function has a few useful input filters.
This function can replace GetExcelTable.ps1 file.

### CODE REVIEW

**Comment by dfinke** [comment]
Thanks @scriptingstudio! Would you want to add some tests for this?

**Comment by scriptingstudio** [comment]
I need some time to learn Pester, so I am not sure that can produce something useful. 
I will add examples first.

**Comment by scriptingstudio** [comment]
Added 2 files to Examples folder (TableContent.*) and fixed some inconsistencies.

**Comment by dfinke** [comment]
Thanks for the PR!
Lots going on in here. Tough to merge without unit tests.

Questions:
1. Is there an advantage *not* using `Open-ExcelPackage`?
2. `ConvertFrom-ExcelColumnName` vs `Get-ExcelColumnName`?

I stopped here for now

**Comment by scriptingstudio** [comment]
1. `Open-ExcelPackage` can be surely used. The function is based on your code, so I left it as is.
2. `ConvertFrom-ExcelColumnName` and `Get-ExcelColumnName` are absolutely opposite. `Get-ExcelColumnName` returns a column name and `ConvertFrom-ExcelColumnName` - column number.

I am very busy all summer, and may be september, at home and at work, so I put it off for awhile.

**Pull request closed without merging**
