### PR TITLE
Internal hyperlinks, reworked format parameters, unhide in export Excel

### PR DESCRIPTION
**Pull request by jhoneill**

### CODE REVIEW

**Comment by dfinke** [comment]
@jhoneill not sure what is going on with the `readme.md` the last few times it has not picked up the changes in master

**Comment by jhoneill** [comment]
In the Set-Row_Set-Column-SetFormat.tests.ps1 line 38 works on my machine but not in appveyor so I commented it out. 

I tried various things but couldn't insert this into the readme.md

# New to 25th July
- Added color parameter completer to a few places where it was missing (Add-ConditionalFormatting/PatternColor  New-ConditionalText PatternColor&BackgroundColor) 
- Changed charting.ps1 and examples\charts\*.ps1 to use New-ExcelChartDefinition instead of New-ExcelChart
- Quick charts in Export-excel were too wide (now 800 pixels instead of 1200), and now support ShowPercent, ShowCategory and NoLegend Parameters 
- Fixed bug in Add-ExcelChart where XAxisPosition and YAxisPostion would not be set correctly 
- Fixed bug in Set-Format where enums with a value of zero, or zero numbers would not be set; added functionality to set-format to support -bold:$false -italic:$false etc.  (see #400) 
- Changed HideSheet in Export-Excel to support wildcards, and added UnhideSheet. (also #400) 
- Added returnRange support to set-Column and Set-row
- Added tests for better coverage (now at >80% average - set-row/colum set-format less than 80%) , and tweaked some tests to use few rows and/or columns for speed

**Comment by dfinke** [comment]
@jhoneill How did you determine code coverage? I was looking at tools.

**Comment by jhoneill** [comment]
It's not very nice but
 `invoke-pester -CodeCoverage  "..\Export-Excel.ps1", "..\Join-Worksheet.ps1" ,  "..\compare-worksheet.ps1"  , "..\Merge-worksheet.ps1" , ..\Set-Column.ps1 , ..\Set-Row.ps1, ..\SetFormat.ps1, ..\AddConditionalFormatting.ps1   
`

**Comment by dfinke** [comment]
Yeah, not a fan. Good in a pinch. Was looking at the code coverage approach in the PowerShell repo

**Comment by dfinke** [comment]
Haven't seen that trick in a bunch of years :) `[System.Windows.Forms.SendKeys]::Sendwait("%{F4}")`

Running tests on my box I get this. 

```powershell
    Context Setting the background to highlight different rows, use of grid view.
      [-] Error occurred in Context block 5.48s
        ParameterBindingValidationException: Cannot bind argument to parameter 'ExcelPackage' because it is null.
        at <ScriptBlock>, C:\Users\Douglas\Documents\GitHub\ImportExcel\__tests__\Compare-WorkSheet.tests.ps1: line 72
        at Invoke-Blocks, C:\Program Files\WindowsPowerShell\Modules\Pester\4.1.1\Functions\SetupTeardown.ps1: line 140
        at Invoke-TestGroupTeardownBlocks, C:\Program Files\WindowsPowerShell\Modules\Pester\4.1.1\Functions\SetupTeardo
wn.ps1: line 130
        at DescribeImpl, C:\Program Files\WindowsPowerShell\Modules\Pester\4.1.1\Functions\Describe.ps1: line 166
```

**Comment by jhoneill** [comment]
CompareWorksheet.Tests doesn't force load the module from the right path, if it finds the previous release that's the error I get :-)

**Pull request merged**
