### PR TITLE
Fixes Issue #744

### PR DESCRIPTION
**Pull request by edwardmjackson**
Fixes call from ConvertFrom-ExcelToSQLInsert with StartRow parameter

### CODE REVIEW

**Comment by dfinke** [comment]
Had the thought, to add a test that proved this didn't work and then add the alias and the test should pass.

**Comment by edwardmjackson** [comment]
I have added tests, and also remerged the code for https://github.com/dfinke/ImportExcel/pull/732 as it was blocking me

**Comment by dfinke** [comment]
LGTM. @jhoneill ?

**Comment by jhoneill** [comment]
It looks like it is backed out the move from comment based to md help.

**Comment by beckerben** [comment]
I ran into the StartRow error and this fix does work, however i noticed what may be an unrelated issue that also specifying "Header" parm generates "Parameter cannot be processed because the parameter name 'Header' is ambiguous" so I renamed this parm to match "HeaderName" in both ConvertFrom-ExcelData and also ConvertFrom-ExcelToSQLInsert.

**Pull request closed without merging**
