### PR TITLE
Fix for #512 & #525

### PR DESCRIPTION
**Pull request by beckerben**

### CODE REVIEW

**Comment by dfinke** [comment]
LGTM, @jhoneill?

**Comment by jhoneill** [comment]
> LGTM, @jhoneill?

Yes, as far as a I can see "O'Neill" would break before and will be OK now. I don't imagine any side effects.

**Comment by sthoen** [comment]
This bug is still present.  The 7.1.1 code is missing the #732 fix.

"'" + (($record.$propertyName) -replace "'","''") + "'"

**Comment by dfinke** [comment]
@sthoen please open a new issue. This may take a bit. Need to upgrade to the latest version of Pester.

**Comment by sthoen** [comment]
Thanks Doug, I have submitted the issue as #920.

Sebastiaan

**Pull request merged**
