### PR TITLE
Fix for #1188

### PR DESCRIPTION
**Pull request by DarkLite1**
- Fix for #1188 : cannot index into 0 error
- Improved error handling in "Import-Excel" to throw consistent error messages (tests updated too)
- Add a test for producing only one error when "Import-Excel" fails instead of multiple
- Some small typo's fixed

### CODE REVIEW

**Comment by DarkLite1** [comment]
@dfinke is there a reason why this is not merged? Did I miss something?

**Comment by dfinke** [comment]
@DarkLite1 I have not had time to look at it

**Comment by DarkLite1** [comment]
@dfinke can you have a look if this can be implemented? It's no structural change and shouldn't break anything. The only thing it does is report a single error in case there is one instead of also throwing the internal errors separately

**Comment by dfinke** [comment]
Sorry. Took a cursory look. My first thought was folks may be dependent on the error message as is

**Comment by DarkLite1** [comment]
That would seem weird... Being dependent on the error message "Cannot index into a null array":
image

**Comment by dfinke** [comment]
If they try/catch on that. Wouldn't your change break them?

**Comment by DarkLite1** [comment]
It seems logical that if people expect 2 errors and there's only 1 that their expectations are not met. But it seems even more logical to handle the errors inside the function and throw a single consistent error where it's clear that this error is generated within the function, instead of polluting the `$error` array with internal errors coming from `Import-Excel`. This brings even more confusion to the table... 

IMHO no one is relying on an error count in this case. So I see no reason not to include it and have clean error handling.

**Comment by DarkLite1** [comment]
Just for clarity, the `try/catch` clause would still work (see the issue I posted).

**Pull request closed without merging**
