### PR TITLE
Perf improvements for Export-Excel

### PR DESCRIPTION
**Pull request by jhoneill**
I had to roll back the changes I made to the readme so github would accept the changes could be merged. So here .... 
# What's new this time. 
- **Performance improvement to Export-Excel** see #506 and #555. This has meant taking code in `Add-CellValue` back into process block of Export-Excel, as the overhead of calling the function was a lot greater than time executing the code inside it. [Blog post to follow](https://jamesone111.wordpress.com). Some tests are showing a ~10x speed increase. #572 was about a broken #region tag in this part of the code and that has been cleaned up in the process. 
- Export-Excel now has an `-InputObject` parameter (this was previously `-TargetData` , which is now an alias for InputObject).
 If the `inputobject` is an array, each item will be inserted, so you can run `export-excel -inputobject $x` rather than `$x | Export-Excel`, and if it is a `system.data.datatable` object it will be inserted directly rather than cell-by-cell. Send-SQLDataToExcel takes advantage of this new functionality. There are simple tests for these new items
- Export-Excel previously assumed `-Now` if there were no other parameters, it will now assume `-Now` if there is no `-Path` or `-ExcelPackage`.     
- The .PSD1 file now itemizes the items exported by the module (#557)

### CODE REVIEW

**Comment by dfinke** [comment]
@jhoneill Planning on zipping this with updates to the readme and then socializing the new bits for broader testing. Let me know if you want to still churn on this.

**Comment by jhoneill** [comment]
@dfinke saw the twitter thread. It's now ready to go. I have a new, slim-line version of Send-SQLData which uses dynamicparam{} to get the parameters from Export-Excel, so if things get added or removed it stays in sync. That's a dozen lines of code and trying to be too clever I managed to get it to write changes to the parameters of a loaded function, which caused fun and games with the parameter sets. Last nights commit was an effort to fix that before I understood it properly  when I finished I found things were better without it.  
The SQL thing is the end of the churn for this one - so if you want to socialize now's a good time

**Comment by dfinke** [comment]
Version number 6.0.0 ?

**Comment by jhoneill** [comment]
Ooh major version update, I thought that was being saved for linking up with the latest EPPlus.dll ? 100% your call :-)

**Comment by dfinke** [comment]
Yeah, this is significant. When EPPlus is xplat, then v7.0, it'll, match the upcoming PS v7.0 version :)

**Comment by DarkLite1** [comment]
@jhoneill thanks for the blogpost. Indeed, maybe I need to start thinking more like an IT Pro instead of a computer scientist, because in the end I just want to go home too :) I just didn't know the impact was so high when calling the function a million times instead of having the code in the process block. Another thing learned today, thank you.

**Comment by jhoneill** [comment]
@DarkLite1 - you're welcome. It *is* amazing, 1ms here and 1ms there doesn't matter, until you have a million of them and that's 15 minutes. Putting stuff into nice neat functions is still the way to go when you are only calling them a modest number of times .

**Comment by DarkLite1** [comment]
I was just wondering if a `Scriptblock = {}` would be faster than a `Function` in this specific case. It would still allow to read clean code. But if the performance drops again it's not worth it off course.

**Comment by jhoneill** [comment]
@DarkLite1  It's something I've got on my list of things to test (along with using PS classes). 
Actually I've just thought of a quicker way to test it which I'll do when I exit headless-chicken mode :-)

**Comment by ili101** [comment]
``` PowerShell
function Verb-Noun
{
    $null = $i
}

$ScriptBlock = {$null = $i}

class ClassName
{
    Test($i)
    {
        $null = $i
    }
}
$ClassInstance = [ClassName]::new()

class ClassNameStatic
{
    static Test($i)
    {
        $null = $i
    }
}

$Tests = @{
    Flat              = {$null = $i}
    Function          = {Verb-Noun}
    ScriptBlockDot    = {. $ScriptBlock}
    ScriptBlockAnd    = {& $ScriptBlock}
    ScriptBlockInvoke = {$ScriptBlock.InvokeReturnAsIs()}
    ClassInstance     = {$ClassInstance.Test($i)}
    ClassInStatic     = {[ClassNameStatic]::Test($i)}
    
}

$Script = {
    Measure-Command {
        for ($i = 0; $i -lt 100000; $i++)
        {
            _Script_
        }
    }
}

$Results = @()
foreach ($Test in $Tests.GetEnumerator())
{
    $Result = [Ordered]@{Name = $Test.Name}
    for ($TestNum = 1; $TestNum -lt 5; $TestNum++)
    {
        $ResultTime = [ScriptBlock]::Create(($Script -replace '_Script_', $Test.Value)).InvokeReturnAsIs()
        $Result["Test $TestNum"] = $ResultTime
        Write-Verbose ("Name: {0}, Test {1}: {2}" -f $Test.Name, $TestNum, $ResultTime) -Verbose
    }
    $Result['Average'] = ($Result.GetEnumerator() | Where-Object Name -Like 'Test*').Value | Measure-Object -Property TotalSeconds -Average | Select-Object -ExpandProperty Average
    $Results += [PSCustomObject]$Result
}
$Results | Sort-Object -Property Average | Format-Table
```
Results:
```
Name              Test 1           Test 2           Test 3           Test 4               Average
----              ------           ------           ------           ------               -------
Flat              00:00:00.1288110 00:00:00.1236764 00:00:00.1415012 00:00:00.1390463 0.133258725
ClassInStatic     00:00:00.6844199 00:00:00.6780921 00:00:00.6681650 00:00:00.6642505 0.673731875
ClassInstance     00:00:00.7459588 00:00:00.7391587 00:00:00.7447225 00:00:00.7368168   0.7416642
ScriptBlockDot    00:00:01.5764087 00:00:01.6110786 00:00:01.5886947 00:00:01.5879553 1.591034325
ScriptBlockInvoke 00:00:01.9530320 00:00:01.9028416 00:00:01.9047247 00:00:01.8740416 1.908659975
ScriptBlockAnd    00:00:03.1146379 00:00:03.1860680 00:00:03.1556045 00:00:03.1653391 3.155412375
Function          00:00:04.2551641 00:00:04.2063672 00:00:04.2027835 00:00:04.2381170  4.22560795
```

**Comment by dfinke** [comment]
This might make a nice blog post. PS v5.1? Is PS v6.x better?

**Comment by ili101** [comment]
Yes that was on 5.1. Interesting side note the script actually didn't work on 6.2 I needed to add explicit ToString `$Test.Value.ToString()` where in 5.1 it worked without it. So some work may be required moving scripts to Core. 
So this version works on Core:
``` PowerShell
function Verb-Noun
{
    $null = $i
}

function Verb-NounParam
{
    param
    (
        [Int]$i
    )
    $null = $i
}

function Verb-NounPipe
{
    param
    (
        [Parameter(ValueFromPipeline)]
        [Int]$i
    )
    begin
    {
    }
    process
    {
        $null = $i
    }
    end
    {
    }
}

$ScriptBlock = {$null = $i}

class ClassName
{
    Test($i)
    {
        $null = $i
    }
}
$ClassInstance = [ClassName]::new()

class ClassNameStatic
{
    static Test($i)
    {
        $null = $i
    }
}

$Tests = [Ordered]@{
    Flat              = {$null = $i}
    Function          = {Verb-Noun}
    FunctionParam     = {Verb-NounParam -i $i}
    FunctionPipe      = {$i | Verb-NounPipe}
    ScriptBlockDot    = {. $ScriptBlock}
    ScriptBlockAnd    = {& $ScriptBlock}
    ScriptBlockInvoke = {$ScriptBlock.InvokeReturnAsIs()}
    ClassInstance     = {$ClassInstance.Test($i)}
    ClassStatic       = {[ClassNameStatic]::Test($i)}
}

$Script = {
    Measure-Command {
        for ($i = 0; $i -lt 1000000; $i++)
        {
            _Script_
        }
    }
}

$Results = @()
foreach ($Test in $Tests.GetEnumerator())
{
    $Result = [Ordered]@{Name = $Test.Name}
    for ($TestNum = 1; $TestNum -lt 5; $TestNum++)
    {
        $ResultTime = [ScriptBlock]::Create(($Script.ToString() -replace '_Script_', $Test.Value.ToString())).InvokeReturnAsIs()
        $Result["Test $TestNum"] = $ResultTime
        Write-Verbose ("Name: {0}, Test {1}: {2}" -f $Test.Name, $TestNum, $ResultTime) -Verbose
    }
    $Result['Average'] = ($Result.GetEnumerator() | Where-Object Name -Like 'Test*').Value | Measure-Object -Property TotalSeconds -Average | Select-Object -ExpandProperty Average
    $Results += [PSCustomObject]$Result
}
$Results | Sort-Object -Property Average | Format-Table
```
Results on 6.2:
```
Name              Test 1           Test 2           Test 3           Test 4                Average
----              ------           ------           ------           ------                -------
Flat              00:00:01.3098483 00:00:01.3011428 00:00:01.3415053 00:00:01.3707140    1.3308026
ClassStatic       00:00:06.8755267 00:00:06.9209289 00:00:06.9608326 00:00:06.7384613  6.873937375
ClassInstance     00:00:07.5806316 00:00:07.6416325 00:00:07.5750805 00:00:07.6209510    7.6045739
ScriptBlockInvoke 00:00:10.0704042 00:00:09.6795793 00:00:09.4151863 00:00:09.2425907  9.601940125
ScriptBlockDot    00:00:14.4357740 00:00:14.2959977 00:00:14.3401616 00:00:14.2887840 14.340179325
ScriptBlockAnd    00:00:18.9680652 00:00:18.8571368 00:00:18.8282078 00:00:18.7296331 18.845760725
Function          00:00:27.2381089 00:00:27.1557229 00:00:26.6860846 00:00:26.7743435 26.963564975
FunctionParam     00:00:31.0107950 00:00:30.9357609 00:00:30.9934745 00:00:30.7932976    30.933332
FunctionPipe      00:00:41.6640927 00:00:43.3245141 00:00:41.9259585 00:00:41.4085794 42.080786175
```
Nice improvements on ScriptBlockInvoke, ScriptBlockAnd, Function and FunctionParam

Also this is probably the best case scenario, the impact may be different in Export-Excel but this is a good general starting point.

**Comment by dfinke** [comment]
Could be due to the performance improvements on .NET Core too

**Pull request merged**
