### PR TITLE
Title fix (Issues #182 and #89)

### PR DESCRIPTION
**Pull request by jeremytbrun**
This PR is an attempt at fixing both issues #182 and #89.

Attached is a test script to reproduce the issues in old and new code.

[ImportExcelPRSample.zip](https://github.com/dfinke/ImportExcel/files/1349151/ImportExcelPRSample.zip)

### CODE REVIEW

**Comment by dfinke** [comment]
hey @jeremytbrun this is what I get running your changes. Is this right?

image

**Comment by jeremytbrun** [comment]
@dfinke Well that's odd. That is definitely not what I get when I run the sample script I originally attached. Can you provide the exact command you are running?

**Comment by jeremytbrun** [comment]
The sample script I attached should yield this.

image

**Comment by dfinke** [comment]
OK, I'll clone it again and double check my local machine has no other modules.

**Comment by dfinke** [comment]
Weird, `git clone https://github.com/jeremytbrun/ImportExcel.git`. My machine has no other installs and I get the results I posted.

**Comment by jeremytbrun** [comment]
Are you cloning the master repository (copy of yours) or the TitleFix repository?

**Comment by jeremytbrun** [comment]
Sorry, I mean TitleFix branch. That is what contains the fixes. Master branch is merely a clone of yours.

**Comment by dfinke** [comment]
Sorry, my fault. Looks good.  I'll take it through it paces a bit more.

Please could you also update the `readme.md`?

**Comment by dfinke** [comment]
This is great, it's looking good.

**Comment by jeremytbrun** [comment]
Sure, I'll update the readme tonight or tomorrow.

Jeremy

**Comment by jeremytbrun** [comment]
@dfinke  README.md updated. Let me know if there is anything else I should add. Thanks for the pointers!

**Comment by dfinke** [comment]
@jeremytbrun, @DarkLite1 I published a new version to the gallery

**Comment by DarkLite1** [comment]
Good job guys! :+1:

**Pull request merged**
