### PR TITLE
Added support for Pester unit tests.

### PR DESCRIPTION
**Pull request by W1M0R**
Type 'help .\TestImportExcel.ps1' for more information.

### CODE REVIEW

**Comment by W1M0R** [comment]
I tried not to be intrusive with my changes.

Could you verify what happens when you run '& .\TestImportExcel.ps1'? On my side one of the tests are failing because Export-Excel.ps1 (line 113) reports that the variable $AlreadyExists does not exist.

**Comment by W1M0R** [comment]
All tests pass when I first import the ImportExcel module, before I run TestImportExcel.ps1.

**Comment by W1M0R** [comment]
I simplified the pull request by removing unnecessary files. I also moved the Pester test to be alongside the script it tests, to encourage more conventional Pester tests.

**Comment by dfinke** [comment]
Thanks again. Reworked it a bit. Sorry for the delay checking this out, otherwise I would have made the comments here, and waited for your updates and then merged them.

https://github.com/dfinke/ImportExcel/commit/7243181563bbbf12a59ca985e4e1656da6ea1fd3

Great work on the tests! It's an excellent stake in the ground and reference how to build them going forward.

**Comment by W1M0R** [comment]
Thanks!

**Pull request closed without merging**
