### PR TITLE
New Function: Add-CellComment

### PR DESCRIPTION
**Pull request by mhokanson**
I created a new function for adding comments to a cell.

I'm not sure why ImportExcel.psm1 is getting caught up in this PR and don't know how to exclude it.

### CODE REVIEW

**Comment by dfinke** [comment]
Thanks, like the cmdlet. Nott sure what is going on with all the changes. Not comfortable to go through all of that. Also, a few tests would be needed.

**Comment by mhokanson** [comment]
Sounds good. I'll figure out what was going on with that new line thing in the module and issue a new pull request.

**Comment by mhokanson** [comment]
Oh, all those changes were me trying to get caught up on your main branch with my stale fork. I'll try to figure out a way to make it cleaner.

**Comment by dfinke** [comment]
Maybe delete your fork, fork again and go from there?

**Comment by mhokanson** [comment]
I'll try that later tonight.

**Pull request closed without merging**
