### PR TITLE
Add comment functions and tests

### PR DESCRIPTION
**Pull request by mhokanson**
I set up my own Azure pipelines and got all the tests to pass. Hopefully the same happens now.

### CODE REVIEW

**Comment by mhokanson** [comment]
Is there anything else you need for this? 

If you're okay with it I'd like to contribute more to this project. Would writing more Pester tests for other functions be helpful?

**Comment by dfinke** [comment]
Thanks for the contribution. I have been looking at an upgrade to ImportExcel. I'm not sure if I will move forward with my upgrade yet. I wanted to avoid having to do the extra work of pulling over changes in this repo to another.

What else were you thinking of adding?

**Comment by mhokanson** [comment]
At this point I was thinking I'd write Pester tests to help cover more functions in testing.

**Comment by dfinke** [comment]
Thanks @mhokanson. Would love to have them. I'm currently looking at some options and directions to go with the ImportExcel module. It will take a while longer to investigate. I'll let you know when the choice is made. That way double work can be avoided.

Thanks again,

**Comment by dfinke** [comment]
@mhokanson was looking at this. One challenge is I have a private repo where I'm experimenting with some things, and `git cherry-pick` is not my favorite things to do across repos. 

Wanted to put this forward, rather than using `column` `row`. I think keeping it consistent, following `Set-ExcelRange` would be good. Wanted to get your thoughts. Hold off on implementing.

**Comment by mhokanson** [comment]
I like consistency, and if the project is moving towards using ranges instead of column/row then I think that makes sense. I'll see what I can do.

**Comment by mhokanson** [comment]
How about this? What if I support both options by allowing a range _or_ column/row. 

I think I like that route better.

Thoughts?

**Comment by dfinke** [comment]
The project will move forward, depends on if will it include the experiments I'm working out. 

Range, Column, and Row sound good. Range can be `A1` or `B2:C4` etc.

**Pull request closed without merging**
