### PR TITLE
TotalSettings improvements

### PR DESCRIPTION
**Pull request by thkn-hofa**
- [Added new function 'Set-CellComment'](https://github.com/dfinke/ImportExcel/commit/652a6111376adaf3f0d5a8655af0acc09659779b)
- [Changed TotalSettings to TableTotalSettings + Changed the way custom formulas are added + added possibility to add comments tot totals row](https://github.com/dfinke/ImportExcel/commit/ce49038b75ff6c6d07a0c2c0f0ae55db23fbfb5e)
- [Updated Tests](https://github.com/dfinke/ImportExcel/commit/b191f16e3e4f7e276dc3633d1b40b4daf8e72e30)
- [Updated Examples](https://github.com/dfinke/ImportExcel/commit/4c0e7970cf0b767ef9a59bae4aa8aecd5f60d789)
- [Updated Documentation](https://github.com/dfinke/ImportExcel/commit/90bc047267f3e11f5ccf3b12df100a302a112acf)
- [Import-Excel.md: Newlines after ```text because of help build failures](https://github.com/dfinke/ImportExcel/commit/4dfd211bb6c88999d9d5ba44e2be25b5fade9c2f)
- [Changelog update: TableTotalSettings in stead of TotalSettings](https://github.com/dfinke/ImportExcel/commit/5558f487321b8d7ec5564b6dd6bb1414ad727500)
- [Doc update (generate)](https://github.com/dfinke/ImportExcel/commit/c719cc3d3223bbe0ae8418a4d1d88b8acfafb27b)

### CODE REVIEW

**Comment by thkn-hofa** [comment]
Reason for adding the cell comments:

image

**Review by dfinke — COMMENTED** [review]
Did you add a test for this ;-)

I think Range is better because it is consistent with Range in Set-ExcelRange etc.

I do like ColumnLetter and Number. Consistency is preferred.

**Comment by dfinke** [comment]
I like `Set-CellComment`. I was looking at how to put a text indicator.

**Comment by thkn-hofa** [comment]
> Did you add a test for this ;-)
> 
> I think Range is better because it is consistent with Range in Set-ExcelRange etc.
> 
> I do like ColumnLetter and Number. Consistency is preferred.

Test is in Export-Excel.tests.ps1 in Example 10 but no separate test.

I copied Set-CellStyle.ps1, that's how I got to these parameters. I'll add the range parameter.

**Review by dfinke — COMMENTED** [review]
In `Export-Excel` did you hit an issue and had to use `$PSBoundParameters` to check for the `$TotalSettings` param have the two `Add-ExcelTable` calls?

**Comment by thkn-hofa** [comment]
Did you mean: Why did you use an If-Else in this piece of code (lines 214 through 221)?

```powershell
                if ($TableName -or $PSBoundParameters.ContainsKey('TableStyle')) {
                    if ($PSBoundParameters.ContainsKey('TableTotalSettings')) {
                        Add-ExcelTable -Range $ws.Cells[$ws.Dimension] -TableName $TableName -TableStyle $TableStyle -TableTotalSettings $TableTotalSettings
                    }
                    Else {
                        Add-ExcelTable -Range $ws.Cells[$ws.Dimension] -TableName $TableName -TableStyle $TableStyle
                    }
                }
```

If you don't split these up, the Add-ExcelTable function will receive the param 'TableTotalSettings' and even when the value is $Null, it will add the totalsrow ($tbl.ShowTotal = $true):

```powershell
        if     ($PSBoundParameters.ContainsKey('TableTotalSettings'))     {
            $tbl.ShowTotal = $true
            foreach ($k in $TableTotalSettings.keys) {
                # Code redacted for readability
            }
        }
```

It would be better solved by adding a check for the value to not be $Null in Add-ExcelTable and removing the If-Else structures in Export-Excel:

```powershell
        if     ($PSBoundParameters.ContainsKey('TableTotalSettings') -And $null -ne $TableTotalSettings)     {
            $tbl.ShowTotal = $true
            foreach ($k in $TableTotalSettings.keys) {
                # Code redacted for readability
            }
        }
```

Updating now...

**Pull request merged**
