### PR TITLE
added three new Convert items

### PR DESCRIPTION
**Pull request by dieselVtwin**
ImportExcel.psm1 references three new Convert*.ps1 files that Install.ps1 didn't copy down.

### CODE REVIEW

**Comment by DarkLite1** [comment]
@dfinke  this has also been done in #202 , so this can be closed as duplicate.

**Comment by slestak** [comment]
Might be worth merging this.  #202 is a much larger scope.  please who install today get errors on import.

**Comment by DarkLite1** [comment]
Can you give some examples on import errors you receive?

**Comment by slestak** [comment]
Here is the result of ipmo after installing using the iex method on server 2012r2.

```
Windows PowerShell
Copyright (C) 2014 Microsoft Corporation. All rights reserved.

PS C:\Users\romanows> ipmo ImportExcel
. : The term 'C:\Users\romanows\Documents\WindowsPowerShell\Modules\ImportExcel\ConvertFromExcelData.ps1' is not
recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if
a path was included, verify that the path is correct and try again.
At C:\Users\romanows\Documents\WindowsPowerShell\Modules\ImportExcel\ImportExcel.psm1:23 char:3
+ . $PSScriptRoot\ConvertFromExcelData.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\romano...omExcelData.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

. : The term 'C:\Users\romanows\Documents\WindowsPowerShell\Modules\ImportExcel\ConvertFromExcelToSQLInsert.ps1' is
not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or
if a path was included, verify that the path is correct and try again.
At C:\Users\romanows\Documents\WindowsPowerShell\Modules\ImportExcel\ImportExcel.psm1:24 char:3
+ . $PSScriptRoot\ConvertFromExcelToSQLInsert.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\romano...ToSQLInsert.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

. : The term 'C:\Users\romanows\Documents\WindowsPowerShell\Modules\ImportExcel\ConvertToExcelXlsx.ps1' is not
recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if
a path was included, verify that the path is correct and try again.
At C:\Users\romanows\Documents\WindowsPowerShell\Modules\ImportExcel\ImportExcel.psm1:25 char:3
+ . $PSScriptRoot\ConvertToExcelXlsx.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\romano...ToExcelXlsx.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

WARNING: PowerShell 5 is required for plot.ps1
WARNING: PowerShell Excel is ready, except for that functionality
PS C:\Users\romanows>
```

**Comment by DarkLite1** [comment]
Is that with or without using PR #202 ?

**Comment by slestak** [comment]
Without.  I just used branch:master.

Sent from my Windows 10 phone

**Comment by DarkLite1** [comment]
I understand, could you try [my repository](https://github.com/DarkLite1/ImportExcel) just to make sure the issue you have isn't in PR #202 ? I'm quite sure this won't happen with the recent updates. If I'm right, that's another reason to merge ;)

**Comment by slestak** [comment]
I see the issue.  There are two scripts with filelists to install, Install.ps1 and InstallModule.ps1.  https://github.com/dfinke/ImportExcel/commit/b90087bd63a6413eda438e97bd36a9cb55a6c911 was applied to only the latter.

I used the install instructions that used iex to run Install.ps1.

**Comment by DarkLite1** [comment]
Yes, these have also been added to install.ps1 and installModule.ps1 in #202

**Comment by DarkLite1** [comment]
@dfinke I think this PR should be closed as it's now fixed in the current release. However, might need to start another question to merge `Install.ps1` and `InstallModule.ps1` in one file as it references the same files, which duplicates code,

**Pull request closed without merging**
