### PR TITLE
Master

### PR DESCRIPTION
**Pull request by jhoneill**
I've added a Compare-Worksheet function 
Cleaned up the color completers, and added added some comments about the date format

### CODE REVIEW

**Comment by jhoneill** [comment]
Managed to break the code just before I sent it <facepalm>.  Now fixed.  Note to self run a full test pass after that "one last thing"

**Comment by jhoneill** [comment]
Compare worksheet has a number of bug fixes, polish and supports more compare options

**Comment by jhoneill** [comment]
Fixed color completer not completing some parameters and reworked the grid view part of compare-worksheet.

**Comment by dfinke** [comment]
Closing. Looks like my pull/push worked.

**Pull request closed without merging**
