### PR TITLE
Add option to skip hidden/filtered rows

### PR DESCRIPTION
**Pull request by joelfish**
Add a switch parameter to skip hidden rows
Filter out hidden row indices after all other conditionals (header, startrow, dataonly, etc) have been processed for simplicity

### CODE REVIEW

**Comment by dfinke** [comment]
Looks like a good feature. Please could you add a test for this so that we can be sure it works, and then also have a way to make it works in the future.

**Comment by joelfish** [comment]
Thanks for the feedback! I've done tons of Powershell over the years, but
this is my first submission to someone else's work so I'm feeling my way
through it. Thanks for the patience. Any reference information you could
direct me to regarding the tests would be appreciated.

Also, thanks for this module. Love it and have used it for ages.

Joel Phillips

**Comment by dfinke** [comment]
Great, take your time, no rush, and ask questions. Check out https://github.com/dfinke/ImportExcel/tree/master/__tests__. Use `Invoke-Pester` to run the tests. Do a `cd __tests__` in where you cloned the ImportExcel. Then add a ps1 file, follow the name pattern. Initially, you'll want to create an xlsx set up so you can test that your logic works.

**Comment by joelfish** [comment]
Very cool thanks so much!

**Comment by dfinke** [comment]
Looking good. Please add one more test, to make sure the records you get back  have the correct data from the rows that are not hidden.

**Comment by dfinke** [comment]
Thanks, looks good. Will be merging and publishing soon. Thanks again for the contribution.

**Comment by joelfish** [comment]
Awesome! Thanks so much for your help!

**Comment by derricksmith** [comment]
Noticed this not merged.  Any plans to merge?

**Comment by joelfish** [comment]
I still use this module daily and would still like this feature to be merged, but did my part (I think) and have just left it to the process.

**Comment by derricksmith** [comment]
@dfinke , this is a valuable feature.  Can you merge?

**Pull request closed without merging**
