### PR TITLE
Update help for GroupDateRow parameter

### PR DESCRIPTION
**Pull request by stahler**
Small change to correct help for GroupDateRow parameter.
BTW - favorite module!

### CODE REVIEW

**Comment by dfinke** [comment]
Thanks Wes. Any reason you closed it?

**Comment by stahler** [comment]
D'oh!  My mistake!

**Comment by dfinke** [comment]
@jhoneill Is there a helper script to update the help with PlatyPS?

**Comment by jhoneill** [comment]
Kind of in my PS-CI.ps1 I have

```PowerShell
    if ((Test-Path -PathType Container "mdHelp") -and -not $SkipHelp) {
        if (-not (Get-Module -ListAvailable platyPS)) {
            'Installing Platyps to build help files'
            Install-Module -Name platyPS -Force -SkipPublisherCheck
        }
        $platypsInfo = Import-Module platyPS  -PassThru -force
        Get-ChildItem .\mdHelp -Directory | ForEach-Object {
           'Building help for language ''{0}'', using {1} V{2}.' -f $_.Name,$platypsInfo.Name, $platypsInfo.Version
            $Null = New-ExternalHelp -Path $_.FullName  -OutputPath (Join-Path $ModulePath $_.Name) -Force
        }
    }
```

**Comment by dfinke** [comment]
Thanks, got it.

**Pull request merged**
