### PR TITLE
Tests improvments and Linux support

### PR DESCRIPTION
**Pull request by ili101**
Integrated https://github.com/ili101/Module.Template. This is a simple template of a module with examples on how to integrate Pester tests and AppVeyor and Azure DevOps Pipelines. this bring:
* AppVeyor and Azure DevOps Pipelines tests on Windows, Linux and Mac (PowerShell, PowerShell Core and PowerShell Core preview).
* Test badges per test:
image
* Test results published so you can see what filed and passed from GitHub, AppVeyor and Azure:
image
* Creates Artifacts in AppVeyor and Azure with the module ready to be installed.
* You can optionally set up manual publish to the PowerShell Gallery in Azure DevOps from the Artifact.
* You can F5 from VSCode to run the tests (Select in the Debug Tab).

**Code Cleanup**
* Fix casing in some of the files names.
* There are 3 files lists in: Install.ps1, ImportExcel.psm1, and filelist.txt that needed to be compared and fixed.
* Tests for features that are not supported yet by EPPlus or by PowerShell Core will be marked as [Pending](https://github.com/pester/Pester/wiki/Set%E2%80%90ItResult).
* If a test cannot run like if Excel is open it will be marked as [Inconclusive](https://github.com/pester/Pester/wiki/Set%E2%80%90ItResult).

**Linux Support**
* In Export-StocksToExcel.ps1 replaced `$env:TEMP` with `[IO.Path]::GetTempPath()` for Linux support.
* In all tests replace `$env:TEMP` with [TestDrive:](https://github.com/pester/Pester/wiki/TestDrive). It's a spacial drive created by the Pester module to help manage the files used by the tests, It also automatically cleans after exiting the scope and is cross-platform.
* As some of the tests use `Get-Service`, `Get-CimInstance` and `Get-Process` that are missing or different on Linux I added Sample data so the test can be run on any platform.

PS
I noticed that there are 2 orphaned files Export-charts.ps1 and GetExcelTable.ps1 that are not referenced anywhere, not sure if intentional or just forgotten to be added to the psm1.

All tests are now running on Linux and Windows I relay dislike "returning" from a test without at last reflating it in the Pester summary, If something is wrong I don't want to see 100% Passed tests. Same goes to skipping the test if Excel is open that now show as "Inconclusive" in the summery.

Regarding https://github.com/dfinke/ImportExcel/pull/666 Skipping all AutoSize tests in Linux, I didn't see any problem with AutoSize on Linux, not sure why it was done, all tests are passing now on Linux to.
None of the tests are now skipped on Linux.
I was wandering why TestDrive: is not used well before the Linux support issue, I think it's a cleaner solution.

@dfinke Regarding your Docker enhancement request, do you think it's something that have a demand for? I didn't see people using modules form Docker. I'm going to check it out anyway as I didn't use Docker before and you piqued my interest (:

### CODE REVIEW

**Comment by dfinke** [comment]
@ili101 Good stuff! 

For Docker, I've been thinking it'd be interesting if I and others could pull an image down, run it and try out the the module, remove it, all without polluting the main box. If it's easy to build that sort of pipeline, then we can experiment to see if it has value.

The Azure DevOps fails, strange.
https://dougfinke.visualstudio.com/ImportExcel/_build/results?buildId=483&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=dac0b392-2308-5704-b9f7-c5b20adf012e&l=9

**Comment by ili101** [comment]
Yes It looks like it run the azure-pipelines.yml from your master and not from the PR.
I don't know if this is a security feature that will use the new azure-pipelines.yml only after merge or maybe you have your Build hard coded and not set to use the yml? can you check in Pipelines > Builds and see if it set to use the yml or maybe create new from yml? I can't check as I have read permission.

**Comment by dfinke** [comment]
Good point, I set that up a while ago using tasks, not yaml. Looks like I need to delete it and setup another pipeline to just the yaml.

**Comment by ili101** [comment]
Ok. ping me when you have the yaml pipeline active and I will push something in here to retrigger the test.

**Comment by ili101** [comment]
Update regarding the AutoFitColumns() problem from https://github.com/dfinke/ImportExcel/pull/666. I just tested it on WSL and also got the problem.
This is fixed by running `sudo apt-get install -y --no-install-recommends libgdiplus libc6-dev` (Solution from https://github.com/VahidN/EPPlus.Core/issues/40)
Surprisingly this didn't came out on AppVeyor and Azure, maybe it's already preinstalled there.

**Comment by dfinke** [comment]
Yeah, saw EPPlus needed that lib from there nuget package. Could be that it is installed. Maybe ImportExcel needs a pre-flight check now?

**Comment by ili101** [comment]
There is actually one test in the psm1 already:
`Write-Warning 'PowerShell 5 is required for plot.ps1'`
Added 2 more for Ubuntu and Mac below it:
```
Write-Warning -Message 'ImportExcel Module Cannot Autosize. Please run the following command to install dependencies: "sudo apt-get install -y --no-install-recommends libgdiplus libc6-dev"'
Write-Warning -Message 'ImportExcel Module Cannot Autosize. Please run the following command to install dependencies: "brew install mono-libgdiplus"'

```

**Comment by dfinke** [comment]
@ili101 I setup a new pipeline, only yml, only PS 5.1. Could you poke the PR to see if it hits the same issue?

**Comment by dfinke** [comment]
@ili101 Thanks, looks like it is working.

**Comment by ili101** [comment]
Looks good. The paused Pipeline "ImportExcel-CI" is still trying to run the test to. Maybe disable it and cancel the 2 test that are queued there.

**Comment by dfinke** [comment]
@ili101 Alright, going merge, a little apprehensive. Thanks for the work, really appreciate it.

**Comment by dfinke** [comment]
@ili101 Merged, I updated the badges. I turned on the new Az DevOps preview, not sure how to index into each job. 

This looks great. What's the best way to chat with you outside of GitHub?

**Comment by ili101** [comment]
appveyor badge need update to:
[Build status](https://ci.appveyor.com/project/dfinke/importexcel)

Skype? ili1011

**Comment by ili101** [comment]
@dfinke After learning to use Docker turned out it was very simple to set up especially because I already have the Artifact ready. 
Take the `Dockerfile` from https://github.com/ili101/Module.Template/tree/master/Tests (uncomment the libgdiplus fix) and put it in your Tests folder.
Then import the `Azure Docker config.json` and follow the **Publish to Docker Hub** instruction in https://github.com/ili101/Module.Template/blob/master/README.md.

**Comment by ili101** [comment]
> This looks great. What's the best way to chat with you outside of GitHub?

@dfinke I started using twitter recently, my user is https://twitter.com/ili_z please add me so we can chat if needed. Thank you.

**Pull request merged**
