### PR TITLE
Import-Excel parameter

### PR DESCRIPTION
**Pull request by DarkLite1**
- Fixed position of `-WorksheetName` parameter
- Added extra Pester tests for parameters

### CODE REVIEW

**Comment by DarkLite1** [comment]
@dfinke if you accept this one it will be possible to omit the parameter names of `-Path` and `-WorksheetName`. So I think it's quite nice to have this because it makes the following just work:

`Import-Excel $Path $Sheet`

**Comment by dfinke** [comment]
Tests pass, good stuff. 
Couple of things, I tried `Import-Excel` on a work box, it worked without specifying the param names. It was an older version but did not check it.

Also, I didn't have the `Assert.psm1` on my box, an the `# requires` caught it, cool. Wonder if that was what caused the issue on appveyor, doubt it, just a data point.

**Comment by DarkLite1** [comment]
On my version of PowerShell, `5.1` it didn't work without setting the parameter `Position=1`. That's why I pushed this PR to fix that.

Yeah, I thought that the `#requires` would be handy to have on top. The `Assert` module is really cool! It has an experimental feature to compare objects (arrays). That's what we use for our tests. Makes life a bit easier and makes it more clear what is the `$Result` and the `$ExpectedResult`.

Really good stuff from the `Pester` guys. Use it from now on in all my production scripts too. Should've done that a long time ago :P

**Comment by DarkLite1** [comment]
Maybe we should do a version bump to `4.0.1` so it's picked up by the `PS Galery`?

**Comment by dfinke** [comment]
When there are more substantial updates, it'll be good to publish. Please, could you update the readme with a sentence on the parameter changes.

**Comment by DarkLite1** [comment]
I understand. I don't think an update of the `README` is needed, because it was a bug as reported by a user. It was also clear from the examples that this was the expected behavior. It would just say that I made a mistake, and I don;t like admitting that ;)

**Pull request merged**
