### PR TITLE
Improved help, minor bugfixes and parameter improvments, more tests

### PR DESCRIPTION
**Pull request by jhoneill**
-PassThru is available in more places. 
-Renamed Set-Format -Row -Column to have Excel in the name (old names as an alias). 
-Set-Format and Add-ConditionalFormat now use "Range" and "Address" in line with EPPlus, and are easier to provide parameters to (backwards compatibility maintained).  Add-ConditionalFormat supports reverse for DataBars (#430)  and wraps strings in quotes when they need it and aren't wrapped (#424)  
-Better handling of links (#426) 
- Move Add named range and Add table functionality out of Export Excel and into separate functions Add-Table supports additional table options (e.g. totals). 
- Add-PivotTable is its own file and now calls Add-ExcelChart to create Pivot charts, and supports a chart definition as a parameter (as well as Address [to locate the pivot *not* on a new page] and PivotTableStyle) 
- ConditionalFormatting, Chart, and Pivot definitions can all be passed as hash tables (the original objects are still supported).   
- Help and example improvements.

### CODE REVIEW

**Comment by DarkLite1** [comment]
Great PR, just one question about the help. It always seems hard to find the help because `Get-Help ...` doesn't always show everything. And I noticed that when you run `Install-Module ExportExcel` you will not get the folder `Examples` (Examples/PivotTable/TableAndPivotTable.ps1). I don't know if this is by design..

**Comment by jhoneill** [comment]
@DarkLite1  I've tried to fix the thing with the help, basically comment based help can be too sensitive to the order things appear in the file, so what looks like perfectly good help gets ignored. 
I wrote myself a tool which I'll share at some stage - which checks that the for each command in a module there is a description, a synopsis, counts the examples and checks there is parameter help for everything which isn't a common parameter, and I've fixed up the bits that I've worked on. 
The examples (and tests) @dfinke  can speak to better, but there is a trade off between having a small download and having all the examples and tests.

**Comment by dfinke** [comment]
@jhoneill is there a Script Analyzer rule that can be enabled for help?

When I started building the Examples, I wanted folks to visit the repo to check things out. The repo examples were what I could point to for "How do I questions..."

**Comment by DarkLite1** [comment]
I actually never really knew there was an Example folder in the first place. Always depended on `Get-Help` to tell me what I need. Anyhow, I believe it deserves more spotlight or should be included in the regular help for those specific CmdLets. #JustMyTwoCents :)

**Comment by jhoneill** [comment]
@DarkLite1  - there's a size where something becomes too big for a help example, but as a general rule, yes, help is the best place, and should be the default things should only go elsewhere if they are too big and unwieldy for on-line help. 

@dfinke  I don't think Script analyser does it (Otherwise a it would go berserk when a lot of things were brought into code). I might have to polish up and share my script :-)

**Comment by dfinke** [comment]
Hmm, maybe in the inline help add links to the examples on GitHub? :)

**Comment by DarkLite1** [comment]
@dfinke that would be the best I think. Just use `.LINK` and point it to the right folder for that CmdLet. I assume each CmdLet has its own folder? Then it would be inline and easy to find. 

Maybe a remark on the home page would be good to, how to find the folder `Example` with some demo's.

**Comment by dfinke** [comment]
@DarkLite1 Yup, be great to get some help on that too ;-)

**Comment by DarkLite1** [comment]
Very busy currently with a big code migration. But when I find some time I'll try to help out 👍

**Comment by ili101** [comment]
I think that if you want to make this the most user friendly the best thing to do is to use the GitHub Wiki.
Create a .md page for each CommandLet in the Wiki with basic explanation and an example or a link to the already created example files, redirect the online help of the CommandLets like "Get-Help Export-Excel -Online" to the appropriate Wiki page.
 
Also README.md got way to long, probably best to split it to a [CHANGELOG.md](https://github.com/PowerShell/PowerShell/blob/master/CHANGELOG.md) file and Wiki pages.

Only downside it will probably take some time to set up :)

**Pull request merged**
