### PR TITLE
support PipelineVariable

### PR DESCRIPTION
**Pull request by ili101**
This is for https://github.com/dfinke/ImportExcel/issues/718
In order to workaround probable PowerShell bug https://github.com/PowerShell/PowerShell/issues/10932 I removed `Begin` and `Process` from `Import-Excel` and added a test for it.
(Ignore the big GitHub "File changes", it just detecting all the indentation changes badly, view changes in VSCode instead)

### CODE REVIEW

**Comment by dfinke** [comment]
Hitting up against PS bugs, nice. Do you know, is this fixed in core etc?

**Comment by ili101** [comment]
I'm on the last preview and it have the same problem

**Comment by dfinke** [comment]
@ili101 thinking of merging @jhoneill changes, then these.

**Comment by jhoneill** [comment]
If we don't have a process block what happens to scenarios like 
`dir timesheets\*.xlsx | import-excel  ...`

**Comment by dfinke** [comment]
Yes. Need to add tests for that scenario first.

**Comment by ili101** [comment]
Sorry, didn't know it was a valid scenario, probably not going to work.
I can add a test and fix it in a few hours when I get home.
Thank you @jhoneill nice catch

**Comment by ili101** [comment]
Did some testing on the existing code, The scenario of multiple paths is not really supported right now
```powershell
Remove-Item -Path $Path1 -ErrorAction SilentlyContinue
Remove-Item -Path $Path2 -ErrorAction SilentlyContinue

$Path1 = Join-Path ([IO.Path]::GetTempPath()) 'test1.xlsx'
$Path2 = Join-Path ([IO.Path]::GetTempPath()) 'test2.xlsx'

# 1 column 2 rows
@(
    [PSCustomObject]@{F1I1 = 'a'}
    [PSCustomObject]@{F1I1 = 'b'}
) | Export-Excel -Path $Path1
# 2 columns 1 row
[PSCustomObject]@{
    F2I1 = 'c'
    F2I2 = 'd'
} | Export-Excel -Path $Path2

$data = $Path1, $Path2 | Import-Excel

'Table Format:'
$data
'List Format:'
$data | Format-List
```
Output:
```
Table Format:

F1I1
----
a
b


List Format:


F1I1 : a

F1I1 : b

F2I1 : c

F2I1 :
```
1. all of the lines from the 2 files are merged into 1 array.
2. The number of columns is set by the first file, if the second file have more columns (In this example)  they are discarded.
3. The number of rows is set by the first file, if the second file less more rows (In this example) they are added as empty.

So we need to decide if we want to support this scenario and if so we need to decide what it will do like if to apply all the input parameters to all of the files and how to output the results? as one big array or nested array for every file.

Also table format (Print to console) of the output will not be usable as PowerShell will distort it, but it's not something we can control:
https://stackoverflow.com/questions/31441054/formatting-issues-missing-data-when-multiple-commands-use-select-object-within

**Comment by dfinke** [comment]
I believe this works as I remember. Let's start here with tests to prove it out and expand it when more scenarios are requested. I like the idea of pipeline variables, to be honest, never used them.

dir C:\Temp\testdata?.xlsx |Import-Excel

[testData1.xlsx](https://github.com/dfinke/ImportExcel/files/3877518/testData1.xlsx)
[testdata2.xlsx](https://github.com/dfinke/ImportExcel/files/3877519/testdata2.xlsx)


```
cola colb
---- ----
   1    3
   2    4
   5    7
   6    8
```

**Comment by ili101** [comment]
Yes merging multiple file with exactly the same columns and exactly the same number of lines works but what are the chances of someone needing something like that? This is more confusing then helpful.

**Comment by dfinke** [comment]
As in James' example, `dir timesheets\*.xlsx`, I'd expect all the timesheets from all employees and they'd be the same in terms of columns. Works for me.

**Comment by ili101** [comment]
Added the 3 tests. same columns & rows count from pipeline and param and PipelineVariable.
Before multiple paths was supported by pipeline, but not from `-Path`. and `-PipelineVariable` didn't worked.
Now all 3 works.

**Comment by dfinke** [comment]
@ili101 What was the workaround you needed to do initially that now works?

**Comment by ili101** [comment]
Initially I just removed the Begin/Process blocks. that make the function behave like everything inside it is in an "end" block so if the pipeline is used you only get the last item in the pipeline.
That's ok if you only take one item from the pipeline, but as we want to support multiple paths that's not good enough.
So I use [$input](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-6#input) that basically collect all the pipeline input that is passed to the function, then use it if exists:
```powershell
    if ($input) {
        $Paths = $input
    }
    elseif ($Path) {
        $Paths = $Path
    }
    else {
        $Paths = ''
    }
```
 and then replace where the "Process" blocks was with a `foreach ($Path in $Paths)` loop.

**Pull request merged**
