### PR TITLE
ConvertTo-ExcelXlsx

### PR DESCRIPTION
**Pull request by NordbergKMD**
Enhancement for https://github.com/dfinke/ImportExcel/issues/143

### CODE REVIEW

**Comment by dfinke** [comment]
Please consider `ConvertFrom-ExcelXls` or `ConvertTo-ExcelXlsx`

**Comment by NordbergKMD** [comment]
That makes complete sense. ConvertTo-ExcelXlsx may be the best choice since it leaves an option to include other formats at a later point in time.
I will adjust and commit.

**Comment by NordbergKMD** [comment]
Any other thoughts?

**Comment by dfinke** [comment]
Thank you for the PR. Much appreciated.

* You don't need `.Extension.ToLower()`, PS is case insensitive.
* Please move the `ValidateScript` to the front part of the script

Rule #2 of the script club, always script less than you have to ;-)

Thanks for the great addition!

**Comment by NordbergKMD** [comment]
> Please move the ValidateScript to the front part of the script

I am not sure I understand what you want me to do.
Are you saying that I should avoid using `ValidateScript` and just implement the validation in the function body?

**Comment by dfinke** [comment]
Yes, that's what I mean.

**Comment by NordbergKMD** [comment]
Alright.
Input validation is now consolidated in the function body.

**Comment by dfinke** [comment]
Terrific, thank you. I'll update the `psm1` and `readme`. Do you have any links you want me to put there, to twitter or something?

**Comment by NordbergKMD** [comment]
Don't mention it - I feel like I am helping myself more than anything. :)
If you want to put up a link to my LinkedIn https://www.linkedin.com/in/mikkelnordberg it'd be great.

**Comment by dfinke** [comment]
Cool, and it is definitely helpful. For bonus points, if you want you can take a swing at adding this new `ps1` to the `psm1` and add it to the `InstallModule,ps1`.

**Comment by dfinke** [comment]
Ooops. Your `ps1` needs changes. Sorry, I should have cloned the PR first and tried it.

You need a `Process {}` block for the `ValueFromPipeline` to work.
Also, the function name is great, I'd prefer if the file name did not have the hyphen `-`.

```powershell

function test {
    param(
        [parameter(Mandatory,ValueFromPipeline)]
        $a
    )

    Process {
    $a
    }
}
```

**Comment by NordbergKMD** [comment]
Will fix and create new PR asap

**Comment by mattcushing** [comment]
I was doing this all by hand and came across this function almost by mistake.  Thank you for creating this!

**Pull request merged**
