### PR TITLE
Add ACE into testing pipeline

### PR DESCRIPTION
**Pull request by royashbrook**
Test adding ACE drivers into the testing pipeline.

### CODE REVIEW

**Comment by royashbrook** [comment]
Testing seems to be working now. No warnings about skipping the tests and test counts are:

- Before:
  - Tests Passed: 219, Failed: 0, Skipped: 21 NotRun: 4
- After:
  - Tests Passed: 234, Failed: 0, Skipped: 6 NotRun: 4

Now just need to get caching working. Once caching is working for this, I may do a different PR to update caching in the pipeline across the board. Updating pester alone looks like it takes 30+ seconds normally to run. Caching that should cut that time off of each job time. =)

**Comment by royashbrook** [comment]
@dfinke this looks good to go. tests are properly running on windows and pscore now. they still skip on the *nix environments. ace download/cache and install seem to be working properly.

**Comment by dfinke** [comment]
Thanks for iterating on that. I will review soon.

**Comment by dfinke** [comment]
Thanks for adding this and working through the issues!

**Pull request merged**
