### PR TITLE
load multiple sheets faster

### PR DESCRIPTION
**Pull request by DreadedTuba**
using += in array is slowing this down.
collecting all $newRow's into $xlBook hash instead of output, then output $xlBook at the end.

### CODE REVIEW

**Comment by dfinke** [comment]
Thanks for the PR! You are correct. Would love to dive deeper. The tests would need to pass first.

**Comment by DreadedTuba** [comment]
fwiw, these tests passed on my local pc, and in my repo actions.
I don't know if you can see this job or not.
https://github.com/DreadedTuba/ImportExcel/actions/runs/4808590671/jobs/8558760529
so i'm puzzled why it might have failed in these checks.

**Comment by moreaki** [comment]
> fwiw, these tests passed on my local pc, and in my repo actions. I don't know if you can see this job or not. https://github.com/DreadedTuba/ImportExcel/actions/runs/4808590671/jobs/8558760529 so i'm puzzled why it might have failed in these checks.

There are quite a few things out of order: https://dougfinke.visualstudio.com/ImportExcel/_build/results?buildId=1349&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=e0810b27-de1e-5f7f-0df7-1a1042e925c2

**Comment by moreaki** [comment]
> fwiw, these tests passed on my local pc, and in my repo actions. I don't know if you can see this job or not. https://github.com/DreadedTuba/ImportExcel/actions/runs/4808590671/jobs/8558760529 so i'm puzzled why it might have failed in these checks.

There are quite a few things out of order: https://dougfinke.visualstudio.com/ImportExcel/_build/results?buildId=1349&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=e0810b27-de1e-5f7f-0df7-1a1042e925c2

**Comment by dfinke** [comment]
Strange that they pass with GitHub Actions and not on Azure.

I was going to deprecate the Azure CI.

Need to carve out time to go deeper.

**Pull request closed without merging**
